[workspace]
resolver = "3"
members = ["crates/qingpdf-core", "crates/qingpdf-cli", "crates/qingpdf-view"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.99"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"
